stages:
  - build
  - sonarqube-check
  - deploy

variables:
  APP_NAME: "siuushop"
  APP_VERSION: "0.0.1-SNAPSHOT"
  DEPLOY_PATH: "/opt/${APP_NAME}"
build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - echo "Building the application"
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/${APP_NAME}-${APP_VERSION}.jar
    expire_in: 1 week
  tags:
    - siuu-shop-shell
  only:
    - main

sonarqube-check:
  stage: sonarqube-check
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Analyzing the code"
    - mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${sqp_7b2e4e089e175ab0c365bffb7d6aa4ff266de5bb}
  tags:
    - siuu-shop-shell
  only:
    - main

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying the application"
    - sudo systemctl stop $APP_NAME || true
    - sudo cp target/${APP_NAME}-${APP_VERSION}.jar ${DEPLOY_PATH}/app.jar
    - sudo systemctl start $APP_NAME
    - sudo systemctl status $APP_NAME
    - echo "Deployed the application"
  tags:
    - siuu-shop-shell
  only:
    - main
