stages:
  - run
variables:
  APP_NAME: "siuushop"
  APP_VERSION: "${CI_COMMIT_SHORT_SHA}"
  DEPLOY_PATH: "/opt/${APP_NAME}"

run:
  stage: run
  variables:
    GIT_STRATEGY: clone
  script:
    - sudo cp -r . ${DEPLOY_PATH}
    - sudo kill -9 $(sudo lsof -t -i:8080) || true
    - sudo nohup mvn -f ${DEPLOY_PATH}/pom.xml spring-boot:run Dproject.version=${APP_VERSION} -Dspring-boot.run.profiles=prod > /dev/null 2>&1 & echo $! > spring-boot.pid
    - sudo systemctl restart nginx
    - echo "Deployed ${APP_NAME} to ${DEPLOY_PATH} with version ${APP_VERSION}"
    - echo "Running ${APP_NAME} with PID $(cat spring-boot.pid)"
  tags:
    - siuu-shop-shell
  only:
    - main

