stages:
  - build
  - sonarqube-check
  - deploy

variables:
  APP_NAME: "siuushop"
  APP_VERSION: "0.0.1-SNAPSHOT"
  DEPLOY_PATH: "/opt/${APP_NAME}"
build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - echo "Building the application"
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/${APP_NAME}-${APP_VERSION}.jar
    expire_in: 1 week
  tags:
    - siuu-shop-shell
  only:
    - main

sonarqube-check:
  stage: sonarqube-check
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=siuuuuu_backend_AZOCXqutQeM2xImMXHjB
  allow_failure: true
  only:
    - main

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying the application"
    - sudo systemctl stop $APP_NAME || true
    - sudo cp target/${APP_NAME}-${APP_VERSION}.jar ${DEPLOY_PATH}/app.jar
    - sudo systemctl start $APP_NAME
    - sudo systemctl status $APP_NAME
    - echo "Deployed the application"
  tags:
    - siuu-shop-shell
  only:
    - main
